### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#124]
There have been many issues created about UX this last week, so I'm consolidating all ideas into this one:

- [ ] Feedback on Flickity sliders (https://github.com/OpenUserCSS/openusercss.org/issues/116)
- [ ] Ratings can be semi-invisible over screenshots (https://github.com/OpenUserCSS/openusercss.org/issues/104)
- [ ] Account page needs redesign with nested routes (https://github.com/OpenUserCSS/openusercss.org/issues/101)
